# Generated by Django 3.2.7 on 2021-10-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao_fbv', '0003_alter_lote_opening_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='category',
            field=models.CharField(choices=[('Automotivos e Peças', 'Automotivos e Peças'), ('Beleza e Cuidados Pessoais', 'Beleza e Cuidados Pessoais'), ('Esporte', 'Esporte'), ('Brinquedos e Jogos', 'Brinquedos e Jogos'), ('Cozinha', 'Cozinha'), ('Eletrônicos', 'Eletrônicos'), ('Games e Consoles', 'Games e Consoles'), ('Livro', 'Livro'), ('Papelaria e Escritório', 'Papelaria e Escritório'), ('Pet Shop', 'Pet Shop'), ('Roupas Calçados e Acessórios', 'Roupas Calçados e Acessórios')], default='', max_length=64),
        ),
    ]
