# Generated by Django 3.2.8 on 2021-11-05 18:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('username', models.CharField(default='', max_length=16)),
                ('email', models.CharField(default='', max_length=256)),
                ('password', models.CharField(default='', max_length=16)),
                ('address', models.CharField(max_length=256)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('rg', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=11)),
                ('card_number', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CompradorDAO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Leiloeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('rg', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=11)),
                ('bank', models.CharField(choices=[('Itau Unibanco S.A.', 'Itau Unibanco S.A.'), ('Banco do Brasil S.A.', 'Banco do Brasil S.A.'), ('Banco Bradesco S.A.', 'Banco Bradesco S.A.'), ('Caixa Economica Federal', 'Caixa Economica Federal'), ('Banco Santander (Brasil) S.A.', 'Banco Santander (Brasil) S.A.'), ('NuBank', 'NuBank'), ('C6', 'C6'), ('Banco Inter S.A.', 'Banco Inter S.A.')], default='', max_length=64)),
                ('agency', models.IntegerField(default=1)),
                ('account_number', models.CharField(max_length=64)),
                ('salary', models.DecimalField(decimal_places=2, default=10, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='LeiloeiroDAO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LoteDAO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('username', models.CharField(default='', max_length=16)),
                ('email', models.CharField(default='', max_length=256)),
                ('password', models.CharField(default='', max_length=16)),
                ('address', models.CharField(max_length=256)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('rg', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=11)),
                ('bank', models.CharField(choices=[('Itau Unibanco S.A.', 'Itau Unibanco S.A.'), ('Banco do Brasil S.A.', 'Banco do Brasil S.A.'), ('Banco Bradesco S.A.', 'Banco Bradesco S.A.'), ('Caixa Economica Federal', 'Caixa Economica Federal'), ('Banco Santander (Brasil) S.A.', 'Banco Santander (Brasil) S.A.'), ('NuBank', 'NuBank'), ('C6', 'C6'), ('Banco Inter S.A.', 'Banco Inter S.A.')], default='', max_length=64)),
                ('agency', models.IntegerField(default=1)),
                ('account_number', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='VendedorDAO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('summary', models.CharField(default='', max_length=512)),
                ('qty', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('Automotivos e Peças', 'Automotivos e Peças'), ('Beleza e Cuidados Pessoais', 'Beleza e Cuidados Pessoais'), ('Esporte', 'Esporte'), ('Brinquedos e Jogos', 'Brinquedos e Jogos'), ('Cozinha', 'Cozinha'), ('Eletrônicos', 'Eletrônicos'), ('Games e Consoles', 'Games e Console'), ('Livro', 'Livro'), ('Papelaria e Escritório', 'Papelaria e Escritório'), ('Pet Shop', 'Pet Shop'), ('Roupas Calçados e Acessórios', 'Roupas Calçados e Acessórios')], default='', max_length=64)),
                ('condition', models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado')], default='', max_length=64)),
                ('min_value', models.DecimalField(decimal_places=2, default=10.0, max_digits=16)),
                ('opening_month', models.CharField(choices=[('Janeiro', 'Janeiro'), ('Fevereiro', 'Fevereiro'), ('Março', 'Março'), ('Abril', 'Abril'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto'), ('Setembro', 'Setembro'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro'), ('Dezembro', 'Dezembro')], default='', max_length=16)),
                ('opening_day', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default=1, max_length=2)),
                ('opening_year', models.CharField(choices=[('2021', '2021'), ('2022', '2022')], default=2021, max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
