# Generated by Django 3.2.7 on 2021-10-01 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leilao_fbv_user', '0002_rename_book_lote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lote',
            old_name='pages',
            new_name='qty',
        ),
        migrations.AddField(
            model_name='lote',
            name='category',
            field=models.CharField(choices=[('automotivo', 'AUTOMOTIVO'), ('beleza', 'BELEZA'), ('esportes', 'ESPORTES'), ('brinquedo', 'BRINQUEDO'), ('cozinha', 'COZINHA'), ('eletronicos', 'ELETRONICOS'), ('games', 'GAMES'), ('livros', 'LIVROS'), ('papelaria e escritorios', 'PAPELARIA'), ('petshop', 'PETSHOP'), ('roupas', 'ROUPAS')], default='automotivo', max_length=64),
        ),
        migrations.AddField(
            model_name='lote',
            name='condition',
            field=models.CharField(choices=[('novo', 'NOVO'), ('usado', 'USADO')], default='novo', max_length=64),
        ),
        migrations.AddField(
            model_name='lote',
            name='min_value',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='lote',
            name='opening_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lote',
            name='summary',
            field=models.CharField(default=django.utils.timezone.now, max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lote',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
