# Generated by Django 3.2.7 on 2021-10-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao_fbv_user', '0007_alter_lote_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='condition',
            field=models.CharField(choices=[('Novo', 'Novo'), ('Usado', 'Usado')], default='', max_length=64),
        ),
    ]
