# Generated by Django 3.2.8 on 2021-10-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao_fbv_user', '0010_comprador_compradordao_leiloeiro_leiloeirodao_vendedor_vendedordao'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='email',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='password',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='username',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='bank',
            field=models.CharField(choices=[('Itau Unibanco S.A.', 'Itau Unibanco S.A.'), ('Banco do Brasil S.A.', 'Banco do Brasil S.A.'), ('Banco Bradesco S.A.', 'Banco Bradesco S.A.'), ('Caixa Economica Federal', 'Caixa Economica Federal'), ('Banco Santander (Brasil) S.A.', 'Banco Santander (Brasil) S.A.'), ('NuBank', 'NuBank'), ('C6', 'C6'), ('Banco Inter S.A.', 'Banco Inter S.A.')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='leiloeiro',
            name='bank',
            field=models.CharField(choices=[('Itau Unibanco S.A.', 'Itau Unibanco S.A.'), ('Banco do Brasil S.A.', 'Banco do Brasil S.A.'), ('Banco Bradesco S.A.', 'Banco Bradesco S.A.'), ('Caixa Economica Federal', 'Caixa Economica Federal'), ('Banco Santander (Brasil) S.A.', 'Banco Santander (Brasil) S.A.'), ('NuBank', 'NuBank'), ('C6', 'C6'), ('Banco Inter S.A.', 'Banco Inter S.A.')], default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='bank',
            field=models.CharField(choices=[('Itau Unibanco S.A.', 'Itau Unibanco S.A.'), ('Banco do Brasil S.A.', 'Banco do Brasil S.A.'), ('Banco Bradesco S.A.', 'Banco Bradesco S.A.'), ('Caixa Economica Federal', 'Caixa Economica Federal'), ('Banco Santander (Brasil) S.A.', 'Banco Santander (Brasil) S.A.'), ('NuBank', 'NuBank'), ('C6', 'C6'), ('Banco Inter S.A.', 'Banco Inter S.A.')], default='', max_length=64),
        ),
    ]
