# Generated by Django 3.2.8 on 2021-10-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao_fbv_user', '0011_auto_20211008_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
