# Generated by Django 3.2.8 on 2021-10-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao_fbv_user', '0012_alter_lote_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='user',
            field=models.CharField(default='', max_length=256),
        ),
    ]
