# Generated by Django 3.2.8 on 2021-10-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao_fbv_user', '0013_lote_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='opening_date',
        ),
        migrations.AddField(
            model_name='lote',
            name='opening_day',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], default=1, max_length=2),
        ),
        migrations.AddField(
            model_name='lote',
            name='opening_month',
            field=models.CharField(choices=[('Janeiro', 'Janeiro'), ('Fevereiro', 'Fevereiro'), ('Março', 'Março'), ('Abril', 'Abril'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto'), ('Setembro', 'Setembro'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro'), ('Dezembro', 'Dezembro')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='lote',
            name='opening_year',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022')], default=2021, max_length=4),
        ),
    ]
