# Generated by Django 3.2.8 on 2021-10-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao_fbv_user', '0014_auto_20211022_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprador',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='comprador',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='comprador',
            name='bank',
        ),
        migrations.AddField(
            model_name='comprador',
            name='card_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='comprador',
            name='email',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='comprador',
            name='password',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='comprador',
            name='username',
            field=models.CharField(default='', max_length=16),
        ),
    ]
