# Generated by Django 3.2.7 on 2021-10-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao_fbv_user', '0006_alter_lote_min_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='condition',
            field=models.CharField(choices=[('Novo', 'NOVO'), ('Usado', 'USADO')], default='', max_length=64),
        ),
    ]
