# Generated by Django 3.2.8 on 2021-11-05 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('username', models.CharField(default='', max_length=16, unique=True)),
                ('email', models.CharField(default='', max_length=256, unique=True)),
                ('password', models.CharField(default='', max_length=16)),
                ('address', models.CharField(max_length=256)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('rg', models.CharField(max_length=9, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('card_number', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CompradorDAO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('username', models.CharField(default='', max_length=16, unique=True)),
                ('email', models.CharField(default='', max_length=256, unique=True)),
                ('password', models.CharField(default='', max_length=16)),
                ('address', models.CharField(max_length=256)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('rg', models.CharField(max_length=9, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('bank', models.CharField(choices=[('Itau Unibanco S.A.', 'Itau Unibanco S.A.'), ('Banco do Brasil S.A.', 'Banco do Brasil S.A.'), ('Banco Bradesco S.A.', 'Banco Bradesco S.A.'), ('Caixa Economica Federal', 'Caixa Economica Federal'), ('Banco Santander (Brasil) S.A.', 'Banco Santander (Brasil) S.A.'), ('NuBank', 'NuBank'), ('C6', 'C6'), ('Banco Inter S.A.', 'Banco Inter S.A.')], default='', max_length=64)),
                ('agency', models.IntegerField(default=1)),
                ('account_number', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendedorDAO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
