# Generated by Django 3.2.7 on 2021-10-01 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao_fbv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(default='', max_length=512)),
                ('qty', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('automotivo_peças', 'Automotivos e Peças'), ('beleza', 'Beleza e Cuidados Pessoais'), ('esportes', 'Esporte'), ('brinquedos', 'Brinquedos e Jogos'), ('cozinha', 'Cozinha'), ('eletronicos', 'Eletronicos'), ('games e consoles', 'Games e Console'), ('livros', 'Livro'), ('papelaria', 'Papelaria e Escritório'), ('petshop', 'Pet Shop'), ('vestuario', 'Roupas Calçados e Acessórios')], default='', max_length=64)),
                ('condition', models.CharField(choices=[('novo', 'NOVO'), ('usado', 'USADO')], default='', max_length=64)),
                ('min_value', models.FloatField(default=10)),
                ('opening_date', models.DateField(default=-2002)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
