# Generated by Django 3.2.8 on 2021-11-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao_fbv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprador',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='email',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='rg',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='comprador',
            name='username',
            field=models.CharField(default='', max_length=16, unique=True),
        ),
    ]
