# Generated by Django 3.2.8 on 2021-11-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao_fbv', '0002_auto_20211101_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='account_number',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='email',
            field=models.CharField(default='', max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='rg',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='username',
            field=models.CharField(default='', max_length=16, unique=True),
        ),
    ]
