# Generated by Django 3.2.7 on 2021-10-01 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao_fbv', '0002_auto_20211001_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='opening_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
