# Generated by Django 3.2.7 on 2021-10-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao_fbv', '0004_alter_lote_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='min_value',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=16),
        ),
    ]
