# Generated by Django 3.2.8 on 2021-10-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao_fbv', '0012_lote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='lote',
            name='user',
            field=models.CharField(default='', max_length=256),
        ),
    ]
