# Generated by Django 3.2.8 on 2021-10-29 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao_fbv', '0014_auto_20211015_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('username', models.CharField(default='', max_length=16)),
                ('email', models.CharField(default='', max_length=256)),
                ('password', models.CharField(default='', max_length=16)),
                ('address', models.CharField(max_length=256)),
                ('birth_date', models.DateField(default=datetime.date.today)),
                ('rg', models.CharField(max_length=9)),
                ('cpf', models.CharField(max_length=11)),
                ('card_number', models.CharField(default='', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CompradorDAO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
